# Default values for test1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

otel:
  repository: otel/opentelemetry-collector:latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 683
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: jaeger-headless:14250
        tls:
          insecure: true
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, jaeger]
   

jager:
  repository: jaegertracing/all-in-one:latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""    

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
ports:
  - port: 16686
    name: web
  - port: 14250
    name: optl-connection
  - port: 4317
    name: grpc  

service:
  type: ClusterIP
  port: 80

env:
   - name: SPAN_STORAGE_TYPE
     value: "badger"
   - name: "COLLECTOR_OTLP_ENABLED"
     value: "true"
   - name: "BADGER_EPHEMERAL"
     value: "false"
   - name: "BADGER_DIRECTORY_VALUE"
     value: "/badger/data"
   - name: "BADGER_DIRECTORY_KEY"
     value: "/badger/key"
ingress:
  name: jager-query
  enabled: false
  className: ngnix
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "*"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

pvc:
  storageclassName: "manual"
  resources:
    requests:
      storage: 10Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


    
nodeSelector: {}

tolerations: []

affinity: {}
