apiVersion: v1
kind: ConfigMap
metadata:
  name: optl-collector-config
  labels:
    app: opentelemetry
    component: optl-collector-config
data:
  optl-collector-config: |
    receivers:
      otlp:
        {{- with .Values.otel.config.data }}
        protocols:
          grpc:
            endpoint: {{ .protocols.grpc.endpoint  }}
          http:
            endpoint: {{ .protocols.http.endpoint  }}
        {{- end }}    
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 683
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: jaeger-headless:14250
        tls:
          insecure: true
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, jaeger]
