apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-optl-collector-config
  labels:
    app: opentelemetry
    component: optl-collector-config
data:
  optl-collector-config: |
    {{ toYaml .Values.otel.config | nindent 4 }}
