apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: opentelemetry
spec:
  {{- with .Values.pvc }}
  volumeMode: Filesystem
  storageClassName: {{ .storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .resources.requests.storage }}
   {{- end }}     
