apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
   app: opentelemetry
   component: optl-collector
   name: jaeger
spec:
  ports:
  - name: query-http
    port: 16686
    protocol: TCP
  selector:
    {{- include "test1.mylabels" . | nindent 4 }}
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
 name: otel
 labels:
   app: opentelemetry
   component: otel-collector
spec:
 type: ClusterIP
 ports:
   - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
     port: 4317
     protocol: TCP
     targetPort: 4317
   - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
     port: 4318
     protocol: TCP
     targetPort: 4318
  #  - name: zpages
  #    port: 55679
  #    protocol: TCP
  #    targetPort: 55679
  #  - name: health-check
  #    port: 13133
  #    protocol: TCP
  #    targetPort: 13133
 selector:
   app: opentelemetry
   name: optl    
